### ISSUE TITLE
clippy warnings regarding use of deprecated lint name `clippy` in generated code

### ISSUE THREAD

**Issue by oysterpack** [mtp401/protoc-grpcio#16]
I get the following clippy warnings
```
warning: lint name `clippy` is deprecated and may not have an effect in the future. Also `cfg_attr(cargo-clippy)` won't be necessary anymore
 --> oysterpack-trust-grpc/src/protos/metrics.rs:6:10
  |
6 | #![allow(clippy)]
  |          ^^^^^^ help: change it to: `clippy::all`
  |
  = note: #[warn(renamed_and_removed_lints)] on by default
```
I am running the latest and greatest versions.

**Comment by mtp401** [comment]
This crate only handles coordinating/running protoc and the grpcio compiler. The latter is what actually generates the code with these lints. You should file an issue with the upstream project if they haven't already fixed this in 5.0.
