### ISSUE TITLE
1.3.0 is breaking, and should be released as 2.0

### ISSUE THREAD

**Issue by Ten0** [mtp401/protoc-grpcio#31]
Because #30 updates grpcio-compiler to a version that generates code non compatible with previous code (hence released as breaking 0.5 -> 0.6), protoc-grpcio now also generates code that is non-compatible with previous code, which makes #30 a breaking change itself.

As such, it should not be released as semver-compatible, as this breaks the projects that depend on it.

So 1.3.0 should be yanked, and this version should be released as 2.0.

**Comment by mtp401** [comment]
0.5 -> 0.6 is not a breaking version increment as defined by semver. I updated the version of this crate in lock step with grpcio-compiler 0.5 -> 0.6 as well as futures 0.1.16 -> 0.3.5. Both of which are minor increments and as such, should be backwards compatible new functionality. I can certainly yank 1.3.0 but the grpcio-compiler maintainers should follow semver. I will file an issue with them.

**Comment by Ten0** [comment]
Rust's semver is slightly different from official semver in that 0.1->0.2 is considered non sever-compatible. They did that in order to allow for representing breaking changes without enforcing people to release a version considered "stable". That is why you might notice I wrote "breaking change" and not "semver-incompatible"

**Comment by Ten0** [comment]
.

**Comment by JakubOnderka** [comment]
But now it is not possible to use grpcio 0.6, because protoc-grpcio 1.3 is yanked and version 2.0 doesn't exists :/

**Comment by Ten0** [comment]
Yes I think we should still re-release this as 2.0

**Comment by mtp401** [comment]
[2.0.0 is up on crates.io](https://crates.io/crates/protoc-grpcio)
