### ISSUE TITLE
"example/diner.proto: No such file or directory"

### ISSUE THREAD

**Issue by mutac** [mtp401/protoc-grpcio#8]
Hi there,

Thanks for your crate!  I'm trying to use it for a project, and I'm having an issue telling protoc where my protos live.  The example in this repo yields a similar for me:

```
$ cd example
$ cargo build
--- stdout
cargo:rerun-if-changed=src/protos

--- stderr
example/diner.proto: No such file or directory
thread 'main' panicked at 'Failed to compile gRPC definitions!: Custom { kind: Other, error: StringError("protoc exited with non-zero exit code") }
```

```
$ protoc --version
libprotoc 3.0.0
$ rustc --version
rustc 1.29.0-nightly (874dec25e 2018-07-21)
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

Do you have any ideas?

**Comment by mtp401** [comment]
I took a look at this over the weekend and was able to reproduce this in the environment you've outlined above. This seems to be an issue specifically with protoc 3.0.0. Newer versions do not have the same issue. Is upgrading the version of protoc you are using an option?

**Comment by mtp401** [comment]
@mutac any thoughts on the above? Is upgrading your version of protoc an option?

**Comment by mutac** [comment]
@mtp401 Hi, sorry for the no-reply.  Yes, that will work for me.  I looked into it a little bit with the version that I had, and was able to get things working by using all absolute paths, however, I'm not familiar enough with protoc to know if that would mess with the build process.  Anyway, thank you for taking a look.  I'll just use a newer version of protoc.
